[package]
name = "native-webview"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
wry = { version = "0.52", default-features = false, features = [
    "os-webview",
    "protocol",
    "x11",
] }
tao = "0.34"
